/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.telas;

import br.com.senac.entidade.Aluno;
import br.com.senac.negocio.AlunoNegocio;
import br.com.senac.verJson.Historico.HistoricoJson;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author vitor.kuhnen
 */
public class AskProfessor extends javax.swing.JFrame {

    Aluno aluno = new Aluno();
    AlunoNegocio alunoNegocio = new AlunoNegocio();

    /**
     * Creates new form TelaAlunos
     */
    public AskProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbMedia = new javax.swing.JLabel();
        lbProfessor = new javax.swing.JLabel();
        lbQtdNotas = new javax.swing.JLabel();
        brGerarMedia = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        varProfessor = new javax.swing.JTextField();
        varQtdNotas = new javax.swing.JTextField();
        varMedia = new javax.swing.JTextField();
        lbAlunos = new javax.swing.JLabel();
        varAlunos = new javax.swing.JTextField();
        lbMatricula = new javax.swing.JLabel();
        varMatricula = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        historico = new javax.swing.JMenu();
        menuHistConsultar = new javax.swing.JMenuItem();
        menuHistDeletar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Senac Notas");

        painel.setBackground(new java.awt.Color(162, 170, 179));

        lbTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Calculo de Média");

        lbMedia.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbMedia.setForeground(new java.awt.Color(0, 0, 0));
        lbMedia.setText("Média:");

        lbProfessor.setBackground(new java.awt.Color(255, 255, 255));
        lbProfessor.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbProfessor.setForeground(new java.awt.Color(0, 0, 0));
        lbProfessor.setText("Professor:");

        lbQtdNotas.setBackground(new java.awt.Color(255, 255, 255));
        lbQtdNotas.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbQtdNotas.setForeground(new java.awt.Color(0, 0, 0));
        lbQtdNotas.setText("Quantas Notas:");

        brGerarMedia.setBackground(new java.awt.Color(255, 255, 255));
        brGerarMedia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        brGerarMedia.setForeground(new java.awt.Color(0, 0, 0));
        brGerarMedia.setText("Gerar Média");
        brGerarMedia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        brGerarMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brGerarMediaActionPerformed(evt);
            }
        });
        brGerarMedia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brGerarMediaKeyPressed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 0, 0));
        btSair.setText("Sair");
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        varProfessor.setBackground(new java.awt.Color(255, 255, 255));
        varProfessor.setForeground(new java.awt.Color(0, 0, 0));

        varQtdNotas.setBackground(new java.awt.Color(255, 255, 255));
        varQtdNotas.setForeground(new java.awt.Color(0, 0, 0));

        varMedia.setBackground(new java.awt.Color(255, 255, 255));
        varMedia.setForeground(new java.awt.Color(0, 0, 0));

        lbAlunos.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbAlunos.setForeground(new java.awt.Color(0, 0, 0));
        lbAlunos.setText("Alunos:");

        varAlunos.setBackground(new java.awt.Color(255, 255, 255));
        varAlunos.setForeground(new java.awt.Color(0, 0, 0));

        lbMatricula.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lbMatricula.setText("Matricula:");

        varMatricula.setBackground(new java.awt.Color(255, 255, 255));
        varMatricula.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbTitulo))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMedia)
                            .addComponent(lbAlunos)))
                    .addComponent(lbQtdNotas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varQtdNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(varAlunos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(varMedia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(brGerarMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btSair)
                .addGap(140, 140, 140))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbTitulo)
                .addGap(30, 30, 30)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProfessor)
                    .addComponent(varProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatricula)
                    .addComponent(varMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtdNotas)
                    .addComponent(varQtdNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMedia)
                    .addComponent(varMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAlunos)
                    .addComponent(varAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brGerarMedia)
                    .addComponent(btSair))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        historico.setText("Histórico");

        menuHistConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planilha-opcao.png"))); // NOI18N
        menuHistConsultar.setText("Consultar");
        menuHistConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistConsultarActionPerformed(evt);
            }
        });
        historico.add(menuHistConsultar);

        menuHistDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir-opcao.png"))); // NOI18N
        menuHistDeletar.setText("Deletar");
        menuHistDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistDeletarActionPerformed(evt);
            }
        });
        historico.add(menuHistDeletar);

        jMenuBar1.add(historico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void menuHistConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistConsultarActionPerformed
        new HistoricoJson().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuHistConsultarActionPerformed

    private void menuHistDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistDeletarActionPerformed
        String historico = JOptionPane.showInputDialog("Informe sua matricula para deletar!");
        String result = alunoNegocio.deletarJson(historico);
        if (result == "1") {
            JOptionPane.showMessageDialog(null, "Informe uma matricula válida!");
            
        } else {
            JOptionPane.showMessageDialog(null, result);
        }


    }//GEN-LAST:event_menuHistDeletarActionPerformed

    private void brGerarMediaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brGerarMediaKeyPressed
        if (varAlunos.getText().isEmpty() && varMedia.getText().isEmpty() && varQtdNotas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe os dados solicitados!!");
        } else{
            int qtdAlunos = Integer.parseInt(varAlunos.getText().trim());
            float media = Float.parseFloat(varMedia.getText().trim());
            int qtdNotas = Integer.parseInt(varQtdNotas.getText().trim());
        

            if (alunoNegocio.validarInfo(varProfessor.getText().trim(), qtdAlunos, media, qtdNotas, varMatricula.getText().trim(), aluno)) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                aluno.setHistorico("Professor: " + aluno.getProfessor() + "\nMédia Definida: " + varMedia.getText()
                    + "\nQuantidade de Alunos: " + varAlunos.getText() + "\nQuantidade de Notas: " + varQtdNotas.getText() + "\n \n");
                new CalculoNota(aluno).setVisible(true);
                dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Confirmar se os campos estão de acordo!!\n \nSeu nome possui mais de 4 letras?\n \nOs campos Aluno, Média e Notas foram informados?");
            }
        }
    }//GEN-LAST:event_brGerarMediaKeyPressed

    private void brGerarMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brGerarMediaActionPerformed
        if (varAlunos.getText().isEmpty() && varMedia.getText().isEmpty() && varQtdNotas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe os dados solicitados!!");
        } else{
            int qtdAlunos = Integer.parseInt(varAlunos.getText().trim());
            float media = Float.parseFloat(varMedia.getText().trim());
            int qtdNotas = Integer.parseInt(varQtdNotas.getText().trim());
        

            if (alunoNegocio.validarInfo(varProfessor.getText().trim(), qtdAlunos, media, qtdNotas, varMatricula.getText().trim(), aluno)) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                aluno.setHistorico("Professor: " + aluno.getProfessor() + "\nMédia Definida: " + varMedia.getText()
                    + "\nQuantidade de Alunos: " + varAlunos.getText() + "\nQuantidade de Notas: " + varQtdNotas.getText() + "\n \n");
                new CalculoNota(aluno).setVisible(true);
                dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Confirmar se os campos estão de acordo!!\n \nSeu nome possui mais de 4 letras?\n \nOs campos Aluno, Média e Notas foram informados?");
            }
        }
        
    }//GEN-LAST:event_brGerarMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AskProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brGerarMedia;
    private javax.swing.JButton btSair;
    private javax.swing.JMenu historico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbAlunos;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbProfessor;
    private javax.swing.JLabel lbQtdNotas;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenuItem menuHistConsultar;
    private javax.swing.JMenuItem menuHistDeletar;
    private javax.swing.JPanel painel;
    private javax.swing.JTextField varAlunos;
    private javax.swing.JTextField varMatricula;
    private javax.swing.JTextField varMedia;
    private javax.swing.JTextField varProfessor;
    private javax.swing.JTextField varQtdNotas;
    // End of variables declaration//GEN-END:variables
}
