/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.telas;

import br.com.senac.entidade.Aluno;
import br.com.senac.negocio.AlunoNegocio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor.kuhnen
 */
public class AskProfessor extends javax.swing.JFrame {

    Aluno aluno = new Aluno();
    AlunoNegocio an = new AlunoNegocio();

    /**
     * Creates new form TelaAlunos
     */
    public AskProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbMedia = new javax.swing.JLabel();
        lbProfessor = new javax.swing.JLabel();
        lbQtdNotas = new javax.swing.JLabel();
        brGerarMedia = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        varProfessor = new javax.swing.JTextField();
        varQtdNotas = new javax.swing.JTextField();
        varMedia = new javax.swing.JTextField();
        lbAlunos = new javax.swing.JLabel();
        varAlunos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Senac Notas");

        painel.setBackground(new java.awt.Color(162, 170, 179));

        lbTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Calculo de Média");

        lbMedia.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbMedia.setForeground(new java.awt.Color(0, 0, 0));
        lbMedia.setText("Média:");

        lbProfessor.setBackground(new java.awt.Color(255, 255, 255));
        lbProfessor.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbProfessor.setForeground(new java.awt.Color(0, 0, 0));
        lbProfessor.setText("Professor:");

        lbQtdNotas.setBackground(new java.awt.Color(255, 255, 255));
        lbQtdNotas.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbQtdNotas.setForeground(new java.awt.Color(0, 0, 0));
        lbQtdNotas.setText("Quantas Notas:");

        brGerarMedia.setBackground(new java.awt.Color(255, 255, 255));
        brGerarMedia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        brGerarMedia.setForeground(new java.awt.Color(0, 0, 0));
        brGerarMedia.setText("Gerar Média");
        brGerarMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brGerarMediaActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 0, 0));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        varProfessor.setBackground(new java.awt.Color(255, 255, 255));
        varProfessor.setForeground(new java.awt.Color(0, 0, 0));

        varQtdNotas.setBackground(new java.awt.Color(255, 255, 255));
        varQtdNotas.setForeground(new java.awt.Color(0, 0, 0));

        varMedia.setBackground(new java.awt.Color(255, 255, 255));
        varMedia.setForeground(new java.awt.Color(0, 0, 0));

        lbAlunos.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbAlunos.setForeground(new java.awt.Color(0, 0, 0));
        lbAlunos.setText("Alunos:");

        varAlunos.setBackground(new java.awt.Color(255, 255, 255));
        varAlunos.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbTitulo))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbMedia)
                                    .addComponent(lbAlunos)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbQtdNotas)))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varQtdNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(varAlunos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(varMedia, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(varProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(brGerarMedia)
                        .addGap(63, 63, 63)
                        .addComponent(btSair)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbTitulo)
                .addGap(30, 30, 30)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProfessor)
                    .addComponent(varProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtdNotas)
                    .addComponent(varQtdNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMedia)
                    .addComponent(varMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAlunos)
                    .addComponent(varAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brGerarMedia)
                    .addComponent(btSair))
                .addGap(165, 165, 165))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void brGerarMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brGerarMediaActionPerformed
        int qtdAlunos = Integer.parseInt(varAlunos.getText().trim());
        float media = Float.parseFloat(varMedia.getText().trim());
        int qtdNotas = Integer.parseInt(varQtdNotas.getText().trim());

        if (an.validarInfo(varProfessor.getText().trim(), qtdAlunos, media, qtdNotas, aluno)) {
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            aluno.setHistorico("Professor: " + aluno.getProfessor() + "\nMédia Definida: " + varMedia.getText()
                    + "\nQuantidade de Alunos: " + varAlunos.getText() + "\nQuantidade de Notas: " + varQtdNotas.getText() + "\n \n");
            new CalculoNota(aluno).setVisible(true);
            dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Confirmar se os campos estão de acordo!!\n \nSeu nome possui mais de 4 letras?\n \nOs campos Aluno, Média e Notas foram informados?");
        }
    }//GEN-LAST:event_brGerarMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AskProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AskProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brGerarMedia;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel lbAlunos;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbProfessor;
    private javax.swing.JLabel lbQtdNotas;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel painel;
    private javax.swing.JTextField varAlunos;
    private javax.swing.JTextField varMedia;
    private javax.swing.JTextField varProfessor;
    private javax.swing.JTextField varQtdNotas;
    // End of variables declaration//GEN-END:variables
}
