/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.telas;

import br.com.senac.entidade.Aluno;
import br.com.senac.negocio.AlunoNegocio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor.kuhnen
 */
public class CalculoNota extends javax.swing.JFrame {

    int[] notas;
    String[] nome;
    private Aluno aluno;
    AlunoNegocio an = new AlunoNegocio();
    float media = 0;

    /**
     * Creates new form CalculoNota
     */
    public CalculoNota() {

        initComponents();

    }

    public CalculoNota(Aluno aluno) {
        notas = new int[aluno.getQtdAlunos()];
        nome = new String[aluno.getQtdAlunos()];
        initComponents();
        this.aluno = aluno;
        btMais.setVisible(false);
        btMenos.setVisible(false);
        varTxResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btMais = new javax.swing.JButton();
        btAdicionaNota = new javax.swing.JButton();
        scrollPainel = new javax.swing.JScrollPane();
        varTxResultado = new javax.swing.JTextArea();
        btMenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel.setBackground(new java.awt.Color(162, 170, 179));

        titulo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Preencha as Informações");

        btMais.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btMais.setText("Ver Mais");
        btMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisActionPerformed(evt);
            }
        });

        btAdicionaNota.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btAdicionaNota.setText("Adicionar notas");
        btAdicionaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionaNotaActionPerformed(evt);
            }
        });

        varTxResultado.setEditable(false);
        varTxResultado.setColumns(20);
        varTxResultado.setForeground(new java.awt.Color(0, 0, 0));
        varTxResultado.setRows(5);
        varTxResultado.setBorder(null);
        scrollPainel.setViewportView(varTxResultado);

        btMenos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btMenos.setText("Ver Menos");
        btMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(titulo))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btAdicionaNota))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btMais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMenos))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addComponent(titulo)
                .addGap(24, 24, 24)
                .addComponent(btAdicionaNota)
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMais)
                    .addComponent(btMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(scrollPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisActionPerformed
        varTxResultado.setVisible(true);
        varTxResultado.setText(aluno.getHistorico());
        btMais.setVisible(false);
        btMenos.setVisible(true);
        
    }//GEN-LAST:event_btMaisActionPerformed

    private void btAdicionaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionaNotaActionPerformed

        for (int i = 0; i < aluno.getQtdAlunos(); i++) {
            aluno.setAluno(JOptionPane.showInputDialog("Informe seu nome!"));
            nome[i] = (String) aluno.getAlunos();

            for (int j = 0; j < aluno.getQtdNotas(); j++) {
                String no = JOptionPane.showInputDialog("Informe sua nota!");
                media += Float.parseFloat(no);
            }
            an.calcularNota(media, aluno);
            notas[i] = (int) aluno.getMedia();
            JOptionPane.showMessageDialog(null, aluno.getAlunos() + " sua média é " + aluno.getMedia());
            media = 0;
        }

        for (int num = 0; num < nome.length; num++) {

            if (notas[num] >= aluno.getDefMedia()) {
                aluno.setHistorico(aluno.getHistorico() + nome[num] + " Você foi aprovado! Sua média é " + notas[num] + "\n");

            } else {
                aluno.setHistorico(aluno.getHistorico() + nome[num] + " Você esta reprovado! Sua média é " + notas[num] + "\n");
            }

        }
        btMais.setVisible(true);

    }//GEN-LAST:event_btAdicionaNotaActionPerformed

    private void btMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenosActionPerformed
        varTxResultado.setVisible(false);
        btMenos.setVisible(false);
        btMais.setVisible(true);
        
    }//GEN-LAST:event_btMenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionaNota;
    private javax.swing.JButton btMais;
    private javax.swing.JButton btMenos;
    private javax.swing.JPanel painel;
    private javax.swing.JScrollPane scrollPainel;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextArea varTxResultado;
    // End of variables declaration//GEN-END:variables
}
